[Flutter] Card 03 - Componetização
annaroncaliowarren/everest-03-crypto-challenge-01 pull request #2
Opened 2022-09-13 18:35 UTC by annaroncaliowarren

**Card 03 - Componetização**  ==>  [https://warren.atlassian.net/browse/EV-776]

Preparação do projeto para uso futuro de uma API, implementando um repositório (inicialmente com dados mockados), usecase e riverpod, também reorganizando as pastas para ser um código limpo e entendível, com os princípios do microfrontend.

![Folders](https://user-images.githubusercontent.com/108409589/189981393-ec4aebbe-a249-454d-bf65-7404908daddd.jpeg)

2022-09-13 19:47 UTC, HenriqueSilvaWarren approved these changes

2022-09-13 19:47 UTC, HenriqueSilvaWarren commented on lib/screens/wallet/widgets/total_customer_currency.dart
> +    bool isVisible = ref.watch(isVisibleProvider.state).state;
Nesse caso, não é necessário evidenciar ref.watch(isVisibleProvider**.state).state**, é possível escrever só ref.watch(isVisibleProvider). **.state).state** ao meu saber é só necessário quando for mudar o valor dentro do state do provider por fora.

2022-09-13 19:47 UTC, HenriqueSilvaWarren commented on lib/screens/wallet/widgets/visibility_icon_button.dart
> +      padding: EdgeInsets.zero,
Para retirar o padding todo do IconButton também é necessário passar como parâmetro constraint: BoxConstraints().

2022-09-13 19:47 UTC, HenriqueSilvaWarren commented on lib/shared/utils/app_assets.dart
>  class AppAssets {
Não é necessária uma classe para chamar os app_assets. Na verdade, é aconselhável mantê-los fora de um escopo de classe para que possam ser acessados do projeto inteiro.

2022-09-13 19:59 UTC, annaroncaliowarren commented on lib/shared/utils/app_assets.dart
>  class AppAssets {
Essa classe foi uma indicação de organização do Carlos Silva, foi alterado de acordo, já que podemos chamar através da classe em todo o projeto (AppAssets().nomeDaVariável).

2022-09-14 14:47 UTC, douglasWarren commented on lib/screens/wallet/widgets/container_top_wallet_screen.dart
> +              color: const Color.fromRGBO(117, 118, 128, 1),
Quando você for usar a mesma cor em varios componentes, é válido adicionar a mesma aos seus assets

2022-09-14 14:50 UTC, douglasWarren approved these changes

2022-09-15 12:46 UTC, CarlosTSIlva requested changes

2022-09-15 12:46 UTC, CarlosTSIlva commented on lib/screens/movements/view/movements_screen.dart
> +  @override
Para que ta usando esse route?

2022-09-15 12:46 UTC, CarlosTSIlva commented on lib/screens/wallet/model/crypto_model.dart
> +    return result;
tu pode fazer direto como... assim n precisa gastar memoria adicionando o item dentro do objeto
```suggestion
    final result = <String, dynamic>{{'shortName': shortName}};
  
    return result;
```

2022-09-15 12:46 UTC, CarlosTSIlva commented on lib/screens/wallet/model/crypto_model.dart
> +    );
em vez do nome map poderia dar coin

2022-09-15 12:46 UTC, CarlosTSIlva commented on lib/shared/widgets/bottom_navigation_bar_app.dart
>  }
Onde usou esse route?

2022-09-15 13:03 UTC, annaroncaliowarren commented on lib/screens/movements/view/movements_screen.dart
> +  @override
Eu coloquei as routes que estão todas na app_routes na utils, para serem utilizadas como rotas nomeadas no futuro, as variáveis static em cada página é apenas para organização e para serem chamadas em todo o projeto pela nomeDaPagina.route.

2022-09-15 13:09 UTC, annaroncaliowarren commented on lib/shared/widgets/bottom_navigation_bar_app.dart
>  }
Essa route indica a tela inicial que pode ser setada na bottom navigation bar, ela está sendo chamada no app_widget como initial route.

2022-09-16 13:19 UTC, CarlosTSIlva approved these changes

2022-09-16 13:23 UTC, merged